# AikidoSec/safe-chain を利用して、悪意ある npm パッケージが含まれていないかチェックする
# https://github.com/AikidoSec/safe-chain
name: Check npm packages by AikidoSec Safe Chain

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - package.json
      - package-lock.json
      - yarn.lock

jobs:
  check-npm-packages-by-aikidosec-safe-chain:
    # 2025/12/18 時点では runner を ubuntu-slim にすると、AikidoSec/safe-chain が動作しない
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      # AikidoSec Safe Chain　をセットアップ
      - name: Install safe-chain
        run: |
          export SAFE_CHAIN_VERSION=1.3.2
          curl -fsSL "https://raw.githubusercontent.com/AikidoSec/safe-chain/$SAFE_CHAIN_VERSION/install-scripts/install-safe-chain.sh" | sh -s -- --ci

      # パッケージに問題がないか検査する
      - name: Install dependencies
        run: |
          yarn install --immutable
